"""`EnvReport` is the one IPC shape the frontend hand-writes, so keep it honest.

Every other type crossing the boundary is generated by ts-rs and guarded by the
`generated types` step, which deletes the directory and regenerates it. This one
is not: it lives in the Tauri shell, which does not depend on ts-rs, and the
TypeScript interface is written by hand in `ipc/index.ts` with a comment saying
so.

A hand-written interface drifts silently and in the worst direction. Add a field
in Rust and forget the TypeScript and it is simply invisible; rename one and the
frontend reads `undefined`, which React renders as nothing at all. The version
this file was written for is exactly that case: a blank where the version should
be is indistinguishable from a panel that has no version in it, which is the
complaint it was added to answer.

So the two are compared here, by name, through serde's camelCase.
"""
from pathlib import Path
import re
import unittest

ROOT = Path(__file__).resolve().parents[2]
RUST = ROOT / 'apps/notes-app/src-tauri/src/commands.rs'
TS = ROOT / 'apps/notes-app/src/ipc/index.ts'


def body(text: str, opening: str) -> str:
    start = text.index(opening) + len(opening)
    return text[start:text.index('\n}', start)]


def camel(name: str) -> str:
    head, *rest = name.split('_')
    return head + ''.join(word.capitalize() for word in rest)


class EnvReportShape(unittest.TestCase):
    def setUp(self):
        rust = RUST.read_text()
        # The attribute is what makes the comparison camelCase; if it ever goes,
        # the names below stop being the names on the wire.
        self.assertIn('#[serde(rename_all = "camelCase")]\npub struct EnvReport {', rust)
        self.fields = {camel(f) for f in re.findall(r'^\s*pub (\w+):', body(rust, 'pub struct EnvReport {'), re.M)}
        declared = body(TS.read_text(), 'export interface EnvReport {')
        declared = re.sub(r'/\*.*?\*/', '', declared, flags=re.S)
        self.declared = set(re.findall(r'^\s*(\w+)\??:', declared, re.M))

    def test_the_two_declare_the_same_fields(self):
        self.assertEqual(self.fields, self.declared)

    def test_the_running_version_is_one_of_them(self):
        # Named rather than left to the set comparison: both sides agreeing that
        # the field is absent would also pass the test above.
        self.assertIn('version', self.fields)
        self.assertIn('version', self.declared)


if __name__ == '__main__':
    unittest.main()
